### ISSUE TITLE
Vassalli 3.7

### ISSUE THREAD

**Issue by Bonobomagno** [UsefullProgrammer/Phi3.7.2Dev#14]
Civiche:
- Feudal Society
- Franchising

Ascension Perk:
-  Shared Destiny

If an overlord has multiple subjects, each subject gains  −1 monthly loyalty for every other subject. This penalty can be removed con le 3 condizioni sopra.
Fare riferimento alle 3 per ripristinarle

Franchising
	
- −25% Empire size from Branch Office
- +0.5 Monthly loyalty from subjects
-Building Can construct Franchise Headquarters holdings
- No Loyalty loss from multiple subjects
- Expansion Prohibited terms of agreement
- Cannot use Limited Diplomacy terms of agreement

Feudal Society

- +1 Unity per Governor level
- −50% Leader cost
- +1 Monthly loyalty from subjects
- Leaders have no upkeep
- No loyalty loss from multiple subjects
- Cannot dismiss leaders
- Cannot use Expansion Prohibited terms of agreement
- Cannot use Limited Diplomacy terms of agreement

Shared Destiny
- +2 Available envoys
- No Loyalty loss from multiple subjects

Suggested:
Franchising: lascio vanilla (ma con l'auto creazione del vassallo, era la feature divertente della mod)
Feudal Society: vanilla, mi sembra forte nella phi
Shared Destiny: 4 envoy/6 envoy

**Comment by UsefullProgrammer** [comment]
Bug non pervenuto.
Fixato localization
